name: Build Release

on:
  push:
    branches: [ main ]
    
  workflow_dispatch:

env:
  EXE_NAME: playground-tfhe

jobs:
  Build_Win:
    runs-on: windows-2019
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Compile
        run: |
          rustup update
          cargo build -r

      - name: Upload traget bin
        uses: actions/upload-artifact@v3
        with:
          name: win.build
          path: target/release/${{ env.EXE_NAME }}.exe


  Build_MacOS:
    runs-on: macos-11
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Compile
        run: |
          rustup update
          rustup target add aarch64-apple-darwin
          cargo build -r --target aarch64-apple-darwin
      
      - name: Codesign for macos build
        # GAS = Github Actions Secret
        # 0. create a new cert at https://developer.apple.com/account/resources/certificates/list.
        # 1. download cert.
        # 2. use keychain app to import the .cer cert in the `login` chains and to export it as a .p12 cert
        # 3. use `base64 the_dev_cert.p12 | pbcopy` to copy cert to clipboard and set to `GAS.MACOS_CERT`, 
        #    the password should be set to `GAS.MACOS_CERT_PWD`.
        # 4. Set the 10 chars in the parenthesis at the suffix of the cert id to `GAS.WWDRTEAMID`.
        # 5. Set the developer's apple id to `GAS.APPLE_ID`.
        # 6. Create an app specific password at https://appleid.apple.com/account/manage and set it to `GAS.APPLEID_APP_PWD`.

        env: 
          MACOS_CERT: ${{ secrets.MACOS_CERT }}
          MACOS_CERT_PWD: ${{ secrets.MACOS_CERT_PWD }}
          KEY_PWD: ${{ secrets.APPLEID_APP_PWD }}
          APPLEID_APP_PWD: ${{ secrets.APPLEID_APP_PWD }}
          WWDRTEAMID: ${{ secrets.WWDRTEAMID }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
        if: ${{ env.APPLE_ID != '' }}
        run: |
          echo "$MACOS_CERT" | base64 -d > certificate.p12
          security create-keychain -p "$KEY_PWD" build.keychain 
          security default-keychain -s build.keychain
          security unlock-keychain -p "$KEY_PWD" build.keychain
          security import certificate.p12 -k build.keychain -P "$MACOS_CERT_PWD" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "$KEY_PWD" build.keychain
          codesign --options runtime --force --deep --sign "$WWDRTEAMID" ./${{ env.EXE_NAME }}

          zip -9 ${{ env.EXE_NAME }}.zip ./${{ env.EXE_NAME }}
          
          xcrun notarytool store-credentials "OLG" --apple-id "$APPLE_ID" --team-id "$WWDRTEAMID" --password "$APPLEID_APP_PWD"
          xcrun notarytool submit ${{ env.EXE_NAME }}.zip --keychain-profile "OLG" --wait

      - name: Upload traget bin
        uses: actions/upload-artifact@v3
        with:
          name: macos.build
          path: ./target/aarch64-apple-darwin/release/${{ env.EXE_NAME }}
